modal done
js-tasks-ru/htmlcss-20210916_serjio-rv pull request #10
Opened 2021-09-28 19:47 UTC by serjio1905

2021-09-28 19:51 UTC, GSemikozov requested changes

2021-09-28 19:51 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: relative;
можно спозиционировать через absolute (на занятии мы использовали паттерн как можно разместить блок четко по середине)

2021-09-29 19:31 UTC, serjio1905 commented on 05-lection3/02-modal/modal.css
> +    position: relative;
done

2021-09-29 19:32 UTC, serjio1905 commented on 05-lection3/02-modal/modal.css
> +    position: relative;
@GSemikozov done

2021-09-29 19:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-04 16:34 UTC, GSemikozov approved these changes

2021-10-04 16:34 UTC, merged