background-image done
js-tasks-ru/htmlcss-20210916_serjio-rv pull request #13
Opened 2021-10-01 18:14 UTC by serjio1905

2021-10-01 18:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-02 16:31 UTC, GSemikozov requested changes

2021-10-02 16:31 UTC, GSemikozov commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 425px) {
лучше выбрать один подход - либо min-width, либо max-width. Если, например, min-width, тогда по дефолту указываем forest_400, дальше при min-width: 768px - forest_768, и так далее вверх

2021-10-03 13:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-03 13:22 UTC, serjio1905 commented on 06-lection4/02-background-image/background-image.css
> +@media screen and (max-width: 425px) {
fixed

2021-10-03 13:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-03 14:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-10-03 17:45 UTC, GSemikozov approved these changes

2021-10-03 17:45 UTC, merged