sceleton done
js-tasks-ru/htmlcss-20210916_serjio-rv pull request #8
Opened 2021-09-26 08:48 UTC by serjio1905

2021-09-26 08:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-26 12:11 UTC, GSemikozov requested changes

2021-09-26 12:11 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
ширину и высоту договоримся не фиксировать

2021-09-26 12:11 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line1 {
.skeleton__line1, .skeleton__line2, .skeleton__long_line - очень не ссистемные и не информативные классы, советую сделать например так: по-первых, создать  .skeleton__line c обзими для всех lines стилей, и во-вторых переименовать классы: модификаторов линий .skeleton__line_long, .skeleton__line_middle, .skeleton__line_short , ширину при этом задавать в процентах

2021-09-26 12:11 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 48px;
здесь тоже не надо фиксировать высоту (а в друг у нас будет настраиваемый компонент и динамически здесь может добавляться не только 2, но и 3-4 линии)

2021-09-27 07:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-27 07:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-27 07:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-27 14:21 UTC, GSemikozov requested changes

2021-09-27 14:21 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_long {
и все-таки еще один момент - по умолчанию line у нас блочный, а значит ширина и так 100%. Тут для _long лучше указать более точно (она чуть более короткая чем 100%)

2021-09-28 08:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-28 08:46 UTC, serjio1905 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_long {
Исправила ширину

2021-09-28 08:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-28 18:56 UTC, GSemikozov approved these changes

2021-09-28 18:56 UTC, merged